package Services;

import Services.common.AppModule;

import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;

import javax.servlet.http.HttpSession;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Feb 26 21:46:36 BDT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for XxOmFinanceVO1.
     * @return XxOmFinanceVO1
     */
    public ViewObjectImpl getXxOmFinanceVO1() {
        return (ViewObjectImpl)findViewObject("XxOmFinanceVO1");
    }
    /**
            * Method to set page parameter value 
            * */

        public void setSessionValues(String orgId, String userId, String respId,
                                     String respAppl) {

            System.out.println("UserId....." + userId);
            System.out.println("OrgID..." + orgId);

            


            if (userId != null) {
                FacesContext fctx = FacesContext.getCurrentInstance();
                ExternalContext ectx = fctx.getExternalContext();
                HttpSession userSession = (HttpSession)ectx.getSession(false);
                userSession.setAttribute("userId", userId);
                 
              //  userSession.setAttribute("orgId", orgId);
               // userSession.setAttribute("respId", respId);
        
                
                
           
            }
        }

}
